
name: Emul C++ CI
on: [push, pull_request]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: # No we will not use ICC; MSVC-Wine is feasible on Azure but only on request
          - c: gcc-9
            cxx: g++-9
          - c: clang-10
            cxx: clang++-10
          - c: clang-11
            cxx: clang++-11
        stdlib_debug: [0, 1]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install compiler
        run: if [ $(echo "$CC" | grep -oP "^clang-") ]; then sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" llvm.sh $(echo "$CC" | grep -oP "clang-\K(\d+)$"); fi
      - name: Install deps
        run: |
          sudo apt install libgl1-mesa-dev libglu1-mesa-dev ninja-build
      - name: configure
        run: mkdir build && pushd build && cmake -G Ninja -DSMCE_STDLIB_DEBUG=${{ matrix.stdlib_debug }} .. && popd
      - name: build
        run: pwd && cmake --build build
    #      - name: test
    #        run: pushd build && ctest && popd
    env:
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cxx }}


  build-windows: # This one needs to be split-off because we want to test both GCC and Clang in Ubuntu
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: configure
        run: mkdir build && cd build && cmake .. && popd
      - name: build
        run: cmake --build build

  build-macos: # We have to split this one off because AppleClang does not yet support Concepts at all
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - c: gcc-9
            cxx: g++-9
          - c: clang-10
            cxx: clang++-10
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          brew update
          brew install --force-bottle coreutils ninja
          if [ $(echo "$CC" | grep -Ei "^clang-") ]; then brew install z3 --force-bottle; brew upgrade --force-bottle llvm; fi
      - name: configure
        run: |
          if [ $(echo "$CC" | grep -Ei "^clang-") ]; then
            export CC=/usr/local/opt/llvm/bin/clang;
            export CXX=/usr/local/opt/llvm/bin/clang++;
          fi
          mkdir build && pushd build && cmake -G Ninja .. && popd
      - name: build
        run: |
          if [ $(echo "$CC" | grep -Ei "^clang-") ]; then
            export CC=/usr/local/opt/llvm/bin/clang;
            export CXX=/usr/local/opt/llvm/bin/clang++;
          fi
          cmake --build build

    env:
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cxx }}
